#!/bin/bash

tc=0
while true
do
  ((tc++))
  echo "Generating test $tc..."
  ./gen > t1
  # ./brute < t1 > sys
  time ./sol < t1 > my
  # diff my sys
  if [ $? -ne 0 ]; then
    echo "Failed on test $tc"
    break
  fi
  echo "OK"
done
