#!/bin/bash

tc=0
while true
do
  ((tc++))
  echo "Generating test $tc..."
  echo "30000 30000" | ./gen > t1
  ./sol < t1 > my
  if [ $? -ne 0 ]; then
    echo "Failed on test $tc"
    break
  fi
  echo "OK"
done
